### ISSUE TITLE
Worker Factories Null in the dagger graph

### ISSUE THREAD

**Issue by ngacho** [weylar/Movie#1]
App fails on start because the factory provider cannot be found.

On further inspection, it appears that the createWorker() method of the MyWorkerFactory provides a wrong workerClassName

**Comment by weylar** [comment]
Thanks

**Comment by ngacho** [comment]
No problem.

It was my first time contributing to someone else's project. I am glad you
found my contribution useful.
Regards,
*Ngacho*.

*"A painting is never finished-It simply stops in interesting places."*
Paul Gauguin.
